name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - release-2.1-upgrade

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build
        run: make build-upgrade
